"""add_explainability_fields_to_behavior_events

Revision ID: 294cd720ae11
Revises: a7f80ac91ac6
Create Date: 2026-07-18 09:07:06.988260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294cd720ae11'
down_revision: Union[str, None] = 'a7f80ac91ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behavior_events', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('behavior_events', sa.Column('search_text', sa.String(), nullable=True))
    op.add_column('behavior_events', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('behavior_events', sa.Column('threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behavior_events', 'threshold')
    op.drop_column('behavior_events', 'reason')
    op.drop_column('behavior_events', 'search_text')
    op.drop_column('behavior_events', 'summary')
    # ### end Alembic commands ###
