"""Add processing job model

Revision ID: 17c389d45905
Revises: 2b4db5b3424e
Create Date: 2026-07-17 22:41:28.882685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c389d45905'
down_revision: Union[str, None] = '2b4db5b3424e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('queued', sa.DateTime(), nullable=True),
    sa.Column('processing', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.Column('failed', sa.DateTime(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('processed_frames', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_jobs_created_at', 'processing_jobs', ['created_at'], unique=False)
    op.create_index('ix_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_index('ix_processing_jobs_video_id', 'processing_jobs', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processing_jobs_video_id', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_status', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_created_at', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    # ### end Alembic commands ###
