"""add_track_model_and_track_id_to_detection

Revision ID: b5809657f22d
Revises: 696678b17890
Create Date: 2026-07-18 00:07:41.468603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5809657f22d'
down_revision: Union[str, None] = '696678b17890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('processing_job_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('first_frame', sa.Integer(), nullable=False),
    sa.Column('last_frame', sa.Integer(), nullable=False),
    sa.Column('first_seen_timestamp', sa.Float(), nullable=False),
    sa.Column('last_seen_timestamp', sa.Float(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('distance_travelled', sa.Float(), nullable=False),
    sa.Column('average_speed', sa.Float(), nullable=False),
    sa.Column('track_duration', sa.Float(), nullable=False),
    sa.Column('frame_coverage', sa.Float(), nullable=False),
    sa.Column('trajectory', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tracks_class_name', 'tracks', ['class_name'], unique=False)
    op.create_index('ix_tracks_processing_job_id', 'tracks', ['processing_job_id'], unique=False)
    op.create_index('ix_tracks_track_id', 'tracks', ['track_id'], unique=False)
    op.create_index('ix_tracks_video_id', 'tracks', ['video_id'], unique=False)
    op.add_column('detection_results', sa.Column('track_id', sa.Integer(), nullable=True))
    op.create_index('ix_detection_results_track_id', 'detection_results', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detection_results_track_id', table_name='detection_results')
    op.drop_column('detection_results', 'track_id')
    op.drop_index('ix_tracks_video_id', table_name='tracks')
    op.drop_index('ix_tracks_track_id', table_name='tracks')
    op.drop_index('ix_tracks_processing_job_id', table_name='tracks')
    op.drop_index('ix_tracks_class_name', table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
