"""add_zones_and_behavior_events

Revision ID: da15607a2d7a
Revises: b5809657f22d
Create Date: 2026-07-18 00:26:01.242736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da15607a2d7a'
down_revision: Union[str, None] = 'b5809657f22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=False),
    sa.Column('polygon_points', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zones_video_id', 'zones', ['video_id'], unique=False)
    op.create_index('ix_zones_zone_type', 'zones', ['zone_type'], unique=False)
    op.create_table('behavior_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.Float(), nullable=False),
    sa.Column('end_timestamp', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_behavior_events_event_type', 'behavior_events', ['event_type'], unique=False)
    op.create_index('ix_behavior_events_track_id', 'behavior_events', ['track_id'], unique=False)
    op.create_index('ix_behavior_events_video_id', 'behavior_events', ['video_id'], unique=False)
    op.create_index('ix_behavior_events_zone_id', 'behavior_events', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_behavior_events_zone_id', table_name='behavior_events')
    op.drop_index('ix_behavior_events_video_id', table_name='behavior_events')
    op.drop_index('ix_behavior_events_track_id', table_name='behavior_events')
    op.drop_index('ix_behavior_events_event_type', table_name='behavior_events')
    op.drop_table('behavior_events')
    op.drop_index('ix_zones_zone_type', table_name='zones')
    op.drop_index('ix_zones_video_id', table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
